// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGeWco6kzB15nen5THnBtXv7NBXjpMhrM',
    appId: '1:433045342775:web:bf78e3dd53185f9af0cdb2',
    messagingSenderId: '433045342775',
    projectId: 'rizz-master-projec',
    authDomain: 'rizz-master-projec.firebaseapp.com',
    storageBucket: 'rizz-master-projec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-vd_utdKCT3jG96YEA2l-mGHHr_UIt9A',
    appId: '1:433045342775:android:fd06c996e47438c8f0cdb2',
    messagingSenderId: '433045342775',
    projectId: 'rizz-master-projec',
    storageBucket: 'rizz-master-projec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_alyL6WhXFMBpumWHbibrHojk4gHgWoY',
    appId: '1:433045342775:ios:ac2f9b785efd73bff0cdb2',
    messagingSenderId: '433045342775',
    projectId: 'rizz-master-projec',
    storageBucket: 'rizz-master-projec.firebasestorage.app',
    iosBundleId: 'com.example.wingmanAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_alyL6WhXFMBpumWHbibrHojk4gHgWoY',
    appId: '1:433045342775:ios:ac2f9b785efd73bff0cdb2',
    messagingSenderId: '433045342775',
    projectId: 'rizz-master-projec',
    storageBucket: 'rizz-master-projec.firebasestorage.app',
    iosBundleId: 'com.example.wingmanAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGeWco6kzB15nen5THnBtXv7NBXjpMhrM',
    appId: '1:433045342775:web:a2f2f76f03774774f0cdb2',
    messagingSenderId: '433045342775',
    projectId: 'rizz-master-projec',
    authDomain: 'rizz-master-projec.firebaseapp.com',
    storageBucket: 'rizz-master-projec.firebasestorage.app',
  );
}
